import React, { useState, useEffect } from 'react';
import axios from 'axios';
import jsPDF from 'jspdf';
import GlitchText from '../GlitchText/GlitchText';
import AnimatedHeading from '../AnimatedHeading/AnimatedHeading';
import './Prescriptions.css';

const PrescriptionList = ({ patientId, userRole, onUploadToMediVault }) => {
  const [prescriptions, setPrescriptions] = useState([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    fetchPrescriptions();
  }, [patientId]);

  const fetchPrescriptions = async () => {
    try {
      const token = localStorage.getItem('token');
      let endpoint = '';

      if (userRole === 'patient') {
        endpoint = `/api/prescriptions/patient/${patientId}`;
      } else if (userRole === 'doctor') {
        endpoint = '/api/prescriptions/doctor';
      }

      const response = await axios.get(endpoint, {
        headers: { Authorization: `Bearer ${token}` }
      });

      if (response.data.success) {
        setPrescriptions(response.data.prescriptions);
      }
    } catch (err) {
      console.error('Error fetching prescriptions:', err);
    } finally {
      setLoading(false);
    }
  };

  const formatDate = (dateString) => {
    const date = new Date(dateString);
    return date.toLocaleDateString('en-US', {
      weekday: 'short',
      year: 'numeric',
      month: 'short',
      day: 'numeric'
    });
  };

  const downloadPDF = (p) => {
    const doc = new jsPDF({ unit: 'pt', format: 'a4' });
    const pageW = doc.internal.pageSize.getWidth();
    const margin = 48;
    let y = 60;

    // Header
    doc.setFillColor(63, 80, 56);
    doc.rect(0, 0, pageW, 44, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(14);
    doc.text('HIPPOCRATES LAB \u2014 PRESCRIPTION', margin, 28);

    y = 70;

    // Date block
    doc.setFillColor(247, 249, 246);
    doc.roundedRect(margin, y, 200, 44, 8, 8, 'F');
    doc.setTextColor(100, 100, 100);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(8);
    doc.text('DATE', margin + 12, y + 16);
    doc.setTextColor(40, 60, 40);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(13);
    doc.text(formatDate(p.date), margin + 12, y + 34);

    // Doctor
    if (p.doctor) {
      doc.setFillColor(247, 249, 246);
      doc.roundedRect(margin + 220, y, 200, 44, 8, 8, 'F');
      doc.setTextColor(100, 100, 100);
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(8);
      doc.text('PHYSICIAN', margin + 232, y + 16);
      doc.setTextColor(40, 60, 40);
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(13);
      doc.text(`Dr. ${p.doctor.name}`, margin + 232, y + 34);
    }

    y += 64;

    // Diagnosis
    doc.setTextColor(156, 163, 175);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(7.5);
    doc.text('DIAGNOSIS', margin, y);
    doc.setTextColor(50, 62, 50);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(11);
    const diagLines = doc.splitTextToSize(p.diagnosis || '\u2014', pageW - margin * 2);
    doc.text(diagLines, margin, y + 14);
    y += 14 + diagLines.length * 14 + 12;

    // Medications
    doc.setTextColor(156, 163, 175);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(7.5);
    doc.text('MEDICATIONS', margin, y);
    y += 14;

    (p.medications || []).forEach((med) => {
      doc.setTextColor(63, 80, 56);
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(10);
      doc.text(med.name || '\u2014', margin, y);
      doc.setTextColor(75, 85, 99);
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(9);
      const details = [med.dosage, med.frequency, med.duration].filter(Boolean).join(' \u2022 ');
      doc.text(details, margin, y + 13);
      if (med.instructions) {
        doc.setTextColor(140, 140, 140);
        doc.setFont('helvetica', 'italic');
        doc.setFontSize(8.5);
        doc.text(med.instructions, margin, y + 24);
        y += 36;
      } else {
        y += 24;
      }
    });

    y += 8;

    // Notes
    if (p.notes) {
      doc.setTextColor(156, 163, 175);
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(7.5);
      doc.text('CLINICAL NOTES', margin, y);
      doc.setTextColor(50, 62, 50);
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(10);
      const noteLines = doc.splitTextToSize(p.notes, pageW - margin * 2);
      doc.text(noteLines, margin, y + 14);
    }

    // Footer
    doc.setFillColor(245, 245, 240);
    doc.rect(0, doc.internal.pageSize.getHeight() - 36, pageW, 36, 'F');
    doc.setTextColor(150, 150, 150);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    doc.text('Generated by Hippocrates Lab Clinical Portal', margin, doc.internal.pageSize.getHeight() - 14);
    doc.text(new Date().toLocaleDateString(), pageW - margin, doc.internal.pageSize.getHeight() - 14, { align: 'right' });

    doc.save(`prescription_${p._id?.slice(-6) || 'record'}.pdf`);
  };

  if (loading) {
    return <div className="prescriptions-loading">Loading prescriptions...</div>;
  }

  return (
    <div className="prescriptions-list-container">
      <header className="prescriptions-list-hero">
        <div className="prescriptions-hero-bg" aria-hidden="true" />
        <div className="prescriptions-hero-content">
          <p className="prescriptions-hero-eyebrow">Prescriptions</p>
          <AnimatedHeading text="Patient prescriptions" />
          <p className="prescriptions-hero-subtitle">Manage patient prescriptions and medications.</p>
        </div>
      </header>

      {prescriptions.length === 0 ? (
        <div className="empty-state-center page-block">
          <GlitchText speed={1} enableShadows enableOnHover={false}>
            No Prescriptions
          </GlitchText>
        </div>
      ) : (
        <div className="prescriptions-grid">
          {prescriptions.map((prescription, index) => (
            <div
              key={prescription._id}
              className="prescription-card-item card-animated"
              style={{ animationDelay: `${index * 0.05}s` }}
            >
              {/* Top: Date + Doctor */}
              <div className="rx-card-top">
                <div className="rx-date-block">
                  <span className="rx-date-label">DATE</span>
                  <span className="rx-date-value">{formatDate(prescription.date)}</span>
                </div>
                {prescription.doctor && (
                  <div className="rx-doctor-tag">
                    Dr. {prescription.doctor.name}
                  </div>
                )}
              </div>

              {/* Diagnosis */}
              <div className="rx-section">
                <span className="v2-label">DIAGNOSIS</span>
                <h4 className="rx-diagnosis-text">{prescription.diagnosis}</h4>
              </div>

              {/* Medications */}
              <div className="rx-section">
                <span className="v2-label">MEDICATIONS</span>
                <div className="rx-med-list">
                  {prescription.medications.map((med, i) => (
                    <div key={i} className="rx-med-row">
                      <span className="rx-med-name">{med.name}</span>
                      <span className="rx-med-detail">
                        {[med.dosage, med.frequency, med.duration].filter(Boolean).join(' \u2022 ')}
                      </span>
                      {med.instructions && (
                        <span className="rx-med-instructions">{med.instructions}</span>
                      )}
                    </div>
                  ))}
                </div>
              </div>

              {/* Notes */}
              {prescription.notes && (
                <div className="rx-section">
                  <span className="v2-label">CLINICAL NOTES</span>
                  <p className="rx-notes-text">{prescription.notes}</p>
                </div>
              )}

              {/* Actions */}
              <div className="rx-actions">
                <button className="download-pdf-btn" onClick={() => downloadPDF(prescription)}>
                  ↓ Download PDF
                </button>
                {userRole === 'patient' && onUploadToMediVault && prescription.medications?.length > 0 && (
                  <button 
                    className="upload-medivault-btn" 
                    onClick={() => onUploadToMediVault(prescription.medications[0].name)}
                  >
                    📤 Upload to MediVault
                  </button>
                )}
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
};

export default PrescriptionList;
